server.port=8081

spring.application.name=patient-service

spring.data.mongodb.uri=mongodb://localhost:27017/medisphere_patient

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

management.endpoints.web.exposure.include=*