server.port=8083

spring.application.name=vitals-service

spring.data.mongodb.uri=mongodb://localhost:27017/medisphere_vitals

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

management.endpoints.web.exposure.include=*
